from tasks.stance_detection import run_stance_detection, infer_stance_detection
from tasks.synthetic_classification import run_synthetic_classification, infer_synthetic_classification

from tasks.utils import *
